# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 714d9a29b146f77440f5dad9b08670f879a80c65f4d8e6b859beda8e2012f85d2804b0e792506ad3e009cfcbd95c243719a39a59d384e4c23c340e82876d01cf

test:
  secret_key_base: 80868a2871ab767f2e2530a16e6621d56022e32767ed437c43fb638859e2c8fc6c0e2a5fc1f1127ff31781b83dd18e9031cadd82204f60140ab4d66d6737e5d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
